<h1>Trabalho 1 de ARQ - G13</h1>

<h1>Identificador automático de idioma</h1>
<p><b>Problema</b>: Dados um texto de entrada, é possível identificar em qual língua o texto está escrito?</p>
<p>
Entrada: "texto qualquer" <br />
Saída: português ou inglês ou francês ou italiano ou...
</p>
<p>&nbsp;</p>

<h2>O processo de Reconhecimento de Padrões</h2>
<p>O objetivo desse trabalho é demonstrar o processo de "construção de atributos" e como ele é fundamental para o <b>Reconhecimento de Padrões (RP)</b>.</p>

<p>Primeiro um conjunto de "amostras" previamente conhecido (classificado)</p>

In [63]:
#
# amostras de texto em diferentes línguas
#
ingles = [
"Hello, how are you?",
"I love to read books.",
"The weather is nice today.",
"Where is the nearest restaurant?",
"What time is it?",
"I enjoy playing soccer.",
"Can you help me with this?",
"I'm going to the movies tonight.",
"This is a beautiful place.",
"I like listening to music.",
"Do you speak English?",
"What is your favorite color?",
"I'm learning to play the guitar.",
"Have a great day!",
"I need to buy some groceries.",
"Let's go for a walk.",
"How was your weekend?",
"I'm excited for the concert.",
"Could you pass me the salt, please?",
"I have a meeting at 2 PM.",
"I'm planning a vacation.",
"She sings beautifully.",
"The cat is sleeping.",
"I want to learn French.",
"I enjoy going to the beach.",
"Where can I find a taxi?",
"I'm sorry for the inconvenience.",
"I'm studying for my exams.",
"I like to cook dinner at home.",
"Do you have any recommendations for restaurants?",
]

espanhol = [
"Hola, ¿cómo estás?",
"Me encanta leer libros.",
"El clima está agradable hoy.",
"¿Dónde está el restaurante más cercano?",
"¿Qué hora es?",
"Voy al parque todos los días.",
"¿Puedes ayudarme con esto?",
"Me gustaría ir de vacaciones.",
"Este es mi libro favorito.",
"Me gusta bailar salsa.",
"¿Hablas español?",
"¿Cuál es tu comida favorita?",
"Estoy aprendiendo a tocar el piano.",
"¡Que tengas un buen día!",
"Necesito comprar algunas frutas.",
"Vamos a dar un paseo.",
"¿Cómo estuvo tu fin de semana?",
"Estoy emocionado por el concierto.",
"¿Me pasas la sal, por favor?",
"Tengo una reunión a las 2 PM.",
"Estoy planeando unas vacaciones.",
"Ella canta hermosamente.",
"El perro está jugando.",
"Quiero aprender italiano.",
"Disfruto ir a la playa.",
"¿Dónde puedo encontrar un taxi?",
"Lamento las molestias.",
"Estoy estudiando para mis exámenes.",
"Me gusta cocinar la cena en casa.",
"¿Tienes alguna recomendación de restaurantes?",
]

portugues = [
"Estou indo para o trabalho agora.",
"Adoro passar tempo com minha família.",
"Preciso comprar leite e pão.",
"Vamos ao cinema no sábado.",
"Gosto de praticar esportes ao ar livre.",
"O trânsito está terrível hoje.",
"A comida estava deliciosa!",
"Você já visitou o Rio de Janeiro?",
"Tenho uma reunião importante amanhã.",
"A festa começa às 20h.",
"Estou cansado depois de um longo dia de trabalho.",
"Vamos fazer um churrasco no final de semana.",
"O livro que estou lendo é muito interessante.",
"Estou aprendendo a cozinhar pratos novos.",
"Preciso fazer exercícios físicos regularmente.",
"Vou viajar para o exterior nas férias.",
"Você gosta de dançar?",
"Hoje é meu aniversário!",
"Gosto de ouvir música clássica.",
"Estou estudando para o vestibular.",
"Meu time de futebol favorito ganhou o jogo.",
"Quero aprender a tocar violão.",
"Vamos fazer uma viagem de carro.",
"O parque fica cheio aos finais de semana.",
"O filme que assisti ontem foi ótimo.",
"Preciso resolver esse problema o mais rápido possível.",
"Adoro explorar novos lugares.",
"Vou visitar meus avós no domingo.",
"Estou ansioso para as férias de verão.",
"Gosto de fazer caminhadas na natureza.",
"O restaurante tem uma vista incrível.",
"Vamos sair para jantar no sábado.",
]

A "amostras" de texto precisa ser "transformada" em <b>padrões</b>

<p>Um padrão é um conjunto de características, geralmente representado por um vetor e um conjunto de padrões no formato de tabela. Onde cada linha é um padrão e as colunas as características e, geralmente, na última coluna a <b>classe</b></p>

In [64]:
import random

pre_padroes = []
for frase in ingles:
  pre_padroes.append( [frase, 'inglês'])

for frase in espanhol:
  pre_padroes.append( [frase, 'espanhol'])

for frase in portugues:
  pre_padroes.append( [frase, 'português'])

random.shuffle(pre_padroes)
print(pre_padroes)

[['O filme que assisti ontem foi ótimo.', 'português'], ['Este es mi libro favorito.', 'espanhol'], ['This is a beautiful place.', 'inglês'], ['El perro está jugando.', 'espanhol'], ['¿Qué hora es?', 'espanhol'], ['Meu time de futebol favorito ganhou o jogo.', 'português'], ['Estou aprendendo a cozinhar pratos novos.', 'português'], ['Gosto de fazer caminhadas na natureza.', 'português'], ['The weather is nice today.', 'inglês'], ['O restaurante tem uma vista incrível.', 'português'], ['Hello, how are you?', 'inglês'], ['Vamos sair para jantar no sábado.', 'português'], ['Me gusta cocinar la cena en casa.', 'espanhol'], ['I enjoy going to the beach.', 'inglês'], ['Adoro passar tempo com minha família.', 'português'], ['El clima está agradable hoy.', 'espanhol'], ['Vamos fazer uma viagem de carro.', 'português'], ['¡Que tengas un buen día!', 'espanhol'], ['Gosto de praticar esportes ao ar livre.', 'português'], ["I'm excited for the concert.", 'inglês'], ['Adoro explorar novos lugares.', 'português'], ['She sings beautifully.', 'inglês'], ['¿Tienes alguna recomendación de restaurantes?', 'espanhol'], ['Where can I find a taxi?', 'inglês'], ['Estou indo para o trabalho agora.', 'português'], ['¿Hablas español?', 'espanhol'], ['Me encanta leer libros.', 'espanhol'], ['What is your favorite color?', 'inglês'], ['Você gosta de dançar?', 'português'], ['Estoy emocionado por el concierto.', 'espanhol'], ['Me gusta bailar salsa.', 'espanhol'], ['Gosto de ouvir música clássica.', 'português'], ['Do you speak English?', 'inglês'], ['Lamento las molestias.', 'espanhol'], ['A festa começa às 20h.', 'português'], ['Estou estudando para o vestibular.', 'português'], ['A comida estava deliciosa!', 'português'], ['Can you help me with this?', 'inglês'], ["I'm studying for my exams.", 'inglês'], ['Preciso resolver esse problema o mais rápido possível.', 'português'], ['I like listening to music.', 'inglês'], ['Quiero aprender italiano.', 'espanhol'], ['Hoje é meu aniversário!', 'português'], ['Você já visitou o Rio de Janeiro?', 'português'], ['O parque fica cheio aos finais de semana.', 'português'], ['I like to cook dinner at home.', 'inglês'], ['Vou visitar meus avós no domingo.', 'português'], ["I'm planning a vacation.", 'inglês'], ["Let's go for a walk.", 'inglês'], ['Necesito comprar algunas frutas.', 'espanhol'], ['I enjoy playing soccer.', 'inglês'], ['Me gustaría ir de vacaciones.', 'espanhol'], ['What time is it?', 'inglês'], ['Disfruto ir a la playa.', 'espanhol'], ['Tengo una reunión a las 2 PM.', 'espanhol'], ['I have a meeting at 2 PM.', 'inglês'], ['Ella canta hermosamente.', 'espanhol'], ["I'm sorry for the inconvenience.", 'inglês'], ['Tenho uma reunião importante amanhã.', 'português'], ['Quero aprender a tocar violão.', 'português'], ['Estou cansado depois de um longo dia de trabalho.', 'português'], ['I need to buy some groceries.', 'inglês'], ['Estou ansioso para as férias de verão.', 'português'], ["I'm going to the movies tonight.", 'inglês'], ['¿Dónde puedo encontrar un taxi?', 'espanhol'], ['O trânsito está terrível hoje.', 'português'], ['Preciso fazer exercícios físicos regularmente.', 'português'], ['Do you have any recommendations for restaurants?', 'inglês'], ['O livro que estou lendo é muito interessante.', 'português'], ['Where is the nearest restaurant?', 'inglês'], ['I want to learn French.', 'inglês'], ['Vou viajar para o exterior nas férias.', 'português'], ['¿Puedes ayudarme con esto?', 'espanhol'], ['¿Me pasas la sal, por favor?', 'espanhol'], ['Hola, ¿cómo estás?', 'espanhol'], ['Have a great day!', 'inglês'], ['Voy al parque todos los días.', 'espanhol'], ['Preciso comprar leite e pão.', 'português'], ['¿Cuál es tu comida favorita?', 'espanhol'], ['Vamos ao cinema no sábado.', 'português'], ['Vamos fazer um churrasco no final de semana.', 'português'], ['¿Dónde está el restaurante más cercano?', 'espanhol'], ['Estoy estudiando para mis exámenes.', 'espanhol'], ['How was your weekend?', 'inglês'], ["I'm learning to play the guitar.", 'inglês'], ['Vamos a dar un paseo.', 'espanhol'], ['¿Cómo estuvo tu fin de semana?', 'espanhol'], ['Estoy planeando unas vacaciones.', 'espanhol'], ['I love to read books.', 'inglês'], ['Could you pass me the salt, please?', 'inglês'], ['Estoy aprendiendo a tocar el piano.', 'espanhol'], ['The cat is sleeping.', 'inglês']]

O DataFrame do pandas facilita a visualização.

In [65]:
import pandas as pd
dados = pd.DataFrame(pre_padroes)
dados

                                       0          1
0   O filme que assisti ontem foi ótimo.  português
1             Este es mi libro favorito.   espanhol
2             This is a beautiful place.     inglês
3                 El perro está jugando.   espanhol
4                          ¿Qué hora es?   espanhol
..                                   ...        ...
87      Estoy planeando unas vacaciones.   espanhol
88                 I love to read books.     inglês
89   Could you pass me the salt, please?     inglês
90   Estoy aprendiendo a tocar el piano.   espanhol
91                  The cat is sleeping.     inglês

[92 rows x 2 columns]

<h1>Construção dos atributos</h1>
<p>Esse é o coração desse trabalho e que deverá ser desenvolvido por vocês. Pensem em como podemos "medir" cadas frase/sentença e extrair características que melhorem o resultado do processo de identificação.<p>
<p>Após a criação de cada novo atributo, execute as etapas seguintes e registre as métricas da matriz de confusão. Principalmente acurácia e a precisão.</p>

In [66]:
NGRAMS_pt = {

    # conectivos e palavras frequentes
    "que",
    "ent",
    "com",
    "par",
    "est",
    "ara",

    # terminações típicas
    "ção",
    "ões",
    "nte",
    "ado",
    "ada",
    "oso",
    "osa",
    "não"

    # padrões muito portugueses
    "nh",
    "nh",
    "lh",
    "ião",
    "ães",

    # verbos comuns
    "ava",
    "iam",
    "mos",
    "rei",

    # artigos/preposições frequentes
    " de",
    " da",
    " do",
    " em",
    " os",
    " as",

    # padrões fonéticos
    "gua",
    "qua",
    "tra",
    "pre",

    # acentuação característica
    "não",
    "ões",
    "çã"
}

NGRAMS_es = {

    # conectivos frequentes
    "que",
    "est",
    "ent",
    "par",
    "con",
    "los",
    "las",

    # artigos/preposições
    " de",
    " la",
    " el",
    " en",
    " un",
    "una",

    # terminações típicas
    "ción",
    "ado",
    "ada",
    "ido",
    "ida",
    "nte",

    # padrões verbais
    "aba",
    "ían",
    "ara",
    "ere",
    "ado",

    # padrões fortes do espanhol
    "ño",
    "ña",
    "ll",
    "ció",
    "ión",

    # palavras extremamente comuns
    "por",
    "del",
    "sus",
    "más",

    # padrões fonéticos
    "gue",
    "qui",
    "tra",
    "pre"
}

NGRAMS_en = {

    # palavras funcionais muito frequentes
    "the",
    "and",
    "ing",
    "ion",
    "ent",
    "for",
    "tha",
    "her",
    "ere",
    "hat",

    # verbos/terminações comuns
    "ing",
    "ted",
    "est",
    "ers",
    "ati",

    # conectivos frequentes
    "wit",
    "you",
    "not",
    "all",
    "thi",

    # padrões fonéticos típicos
    "th",
    "sh",
    "ch",
    "wh",

    # palavras muito frequentes
    "was",
    "are",
    "but",
    "one",
    "out",

    # sequências extremamente inglesas
    "ght",
    "ough",
    "ould",
    "ther"
}

In [67]:
# a entrada é o vetor pre_padroes e a saída desse passo deverá ser "padrões"
import re


ACENTOS_CHAR = ['ã', 'õ', 'á', 'é', 'í', 'ó', 'ú', 'â', 'ê', 'ô', 'à']
CEDILHA_CHAR = ['ç']
N_TIL = ['ñ']

def tamanhoMedioPalavras(texto):
  palavras = texto.split()
  #previne erro de divisão por zero
  if not palavras:
    return 0
  return sum(len(p) for p in palavras) / len(palavras)


def score_char_especial(texto, char_list):
  # conta a ocorrência de caracteres especiais
  texto = texto.lower() 
  return sum(texto.count(c) for c in char_list)
      
def score_ngrams(texto, ngrams_conhecidos):
    texto = texto.lower()
    total = 0
    for ng in ngrams_conhecidos:
        n = len(ng)
        for i in range(len(texto) - n + 1):
            if texto[i:i+n] == ng:
                total += 1
    
    return total
  

def extraiCaracteristicas(frase):
  # frase é um vetor [ 'texto', 'lingua' ]
  texto = frase[0]
  #pattern_regex = re.compile('[^\w+]', re.UNICODE)
  texto = re.sub(r'[^\w\s]', ' ', texto)
  #print(texto)
  caracteristica1=tamanhoMedioPalavras(texto)
  caracteristica2=score_char_especial(texto, ACENTOS_CHAR) 
  caracteristica3=score_char_especial(texto, CEDILHA_CHAR)
  caracteristica4=score_char_especial(texto, N_TIL)
  caracteristica5=score_ngrams(texto, NGRAMS_pt)
  caracteristica6=score_ngrams(texto, NGRAMS_es)
  caracteristica7=score_ngrams(texto, NGRAMS_en)
  
 
  # acrescente as suas funcoes no vetor padrao
  padrao = [caracteristica1, 
            caracteristica2, 
            caracteristica3,
            caracteristica4,
            caracteristica5,
            caracteristica6,
            caracteristica7,
            frase[1] ]
  return padrao


def geraPadroes(frases):
  padroes = []
  for frase in frases:
    padrao = extraiCaracteristicas(frase)
    padroes.append(padrao)
  return padroes

# converte o formato [frase classe] em
# [caracteristica_1, caracteristica_2,... caracteristica n, classe]
padroes = geraPadroes(pre_padroes)

#
# apenas para visualizacao
#print(padroes)

dados = pd.DataFrame(padroes)
dados

           0  1  2  3  4  5  6          7
0   4.142857  1  0  0  3  2  0  português
1   4.200000  0  0  0  1  1  1   espanhol
2   4.200000  0  0  0  0  0  2     inglês
3   4.500000  1  0  0  1  1  2   espanhol
4   3.000000  1  0  0  0  0  0   espanhol
..       ... .. .. .. .. .. ..        ...
87  7.000000  0  0  0  1  3  4   espanhol
88  3.200000  0  0  0  0  0  0     inglês
89  3.857143  0  0  0  0  0  4     inglês
90  4.833333  0  0  0  2  3  1   espanhol
91  4.000000  0  0  0  0  0  3     inglês

[92 rows x 8 columns]

<h2>Treinando o modelo com SVM</h1>
<p>Separando o conjunto de treinamento do conjunto de testes</p>

In [68]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np


#from sklearn.metrics import confusion_matrix

vet = np.array(padroes)
classes = vet[:,-1]         # classes = [p[-1] for p in padroes]
#print(classes)
padroes_sem_classe = vet[:,0:-1]
#print(padroes_sem_classe)
X_train, X_test, y_train, y_test = train_test_split(padroes_sem_classe, classes, test_size=0.25, stratify=classes)

#SVM é sensivel a escala
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

Com os conjuntos separados, podemos "treinar" o modelo usando a SVM.

In [69]:
from sklearn import svm
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

treinador = svm.SVC()  #algoritmo escolhido
modelo = treinador.fit(X_train, y_train)

#
# score com os dados de treinamento
acuracia = modelo.score(X_train, y_train)
print("Acurácia nos dados de treinamento: {:.2f}%".format(acuracia * 100))

#
# melhor avaliar com a matriz de confusão
y_pred = modelo.predict(X_train)
cm = confusion_matrix(y_train, y_pred)
print(cm)
print(classification_report(y_train, y_pred))

#
# com dados de teste que não foram usados no treinamento
print('métricas mais confiáveis')
y_pred2 = modelo.predict(X_test)
cm = confusion_matrix(y_test, y_pred2)
print(cm)
print(classification_report(y_test, y_pred2))

Acurácia nos dados de treinamento: 91.30%
[[18  1  4]
 [ 0 22  0]
 [ 1  0 23]]
              precision    recall  f1-score   support

    espanhol       0.95      0.78      0.86        23
      inglês       0.96      1.00      0.98        22
   português       0.85      0.96      0.90        24

    accuracy                           0.91        69
   macro avg       0.92      0.91      0.91        69
weighted avg       0.92      0.91      0.91        69

métricas mais confiáveis
[[4 1 2]
 [0 8 0]
 [1 0 7]]
              precision    recall  f1-score   support

    espanhol       0.80      0.57      0.67         7
      inglês       0.89      1.00      0.94         8
   português       0.78      0.88      0.82         8

    accuracy                           0.83        23
   macro avg       0.82      0.82      0.81        23
weighted avg       0.82      0.83      0.82        23